name: soft_warts_test_task
description: Test task for SoftWars

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.1.2
  image_picker: ^0.8.7+5
  page_transition: ^2.0.9
  intl: ^0.18.1
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
     - family: SF UI Display
       fonts:
         - asset: assets/fonts/sf-ui-display-medium.otf
           weight: 500
         - asset: assets/fonts/sf-ui-display-semibold.otf
           weight: 600
